# Generated by Django 5.1.3 on 2024-11-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramMaster',
            fields=[
                ('program_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=4)),
                ('program_name', models.CharField(max_length=150)),
                ('program_type', models.CharField(max_length=1)),
                ('program_mode', models.CharField(max_length=1)),
                ('no_of_terms', models.IntegerField(null=True)),
                ('total_credits', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('max_number_of_fail_subjects', models.IntegerField(null=True)),
                ('ug_pg', models.CharField(max_length=2)),
                ('active', models.CharField(max_length=4)),
                ('months_duration_in_english', models.CharField(max_length=100, null=True)),
                ('months_duration_in_hindi', models.CharField(max_length=100, null=True)),
                ('result_system', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'program_master',
            },
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_code', models.CharField(max_length=4)),
                ('entity_id', models.CharField(max_length=8)),
                ('roll_number', models.CharField(max_length=10)),
                ('program_course_key', models.CharField(max_length=14)),
                ('evaluation_id', models.CharField(max_length=3)),
                ('marks', models.IntegerField(null=True)),
                ('grades', models.CharField(max_length=2, null=True)),
                ('pass_fail', models.CharField(max_length=3, null=True)),
                ('course_code', models.CharField(max_length=8)),
                ('semester_start_date', models.DateField()),
                ('semester_end_date', models.DateField()),
            ],
            options={
                'db_table': 'student_marks',
                'unique_together': {('roll_number', 'program_course_key', 'evaluation_id', 'course_code', 'semester_start_date', 'semester_end_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentMarksSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_code', models.CharField(max_length=4)),
                ('entity_id', models.CharField(max_length=8)),
                ('roll_number', models.CharField(max_length=10)),
                ('program_course_key', models.CharField(max_length=14)),
                ('semester_start_date', models.DateField()),
                ('semester_end_date', models.DateField()),
                ('total_internal', models.IntegerField(null=True)),
                ('total_external', models.IntegerField(null=True)),
                ('total_marks', models.IntegerField(null=True)),
                ('course_code', models.CharField(max_length=8)),
                ('internal_grade', models.CharField(max_length=3, null=True)),
                ('external_grade', models.CharField(max_length=3, null=True)),
                ('final_grade_point', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('earned_credits', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'student_marks_summary',
                'unique_together': {('roll_number', 'program_course_key', 'course_code', 'semester_start_date', 'semester_end_date')},
            },
        ),
        migrations.CreateModel(
            name='CourseEvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.CharField(max_length=5)),
                ('evaluation_id', models.CharField(max_length=3)),
                ('evaluation_id_name', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=8)),
                ('maximum_marks', models.IntegerField()),
                ('weightage', models.IntegerField()),
                ('component_full_name', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.programmaster')),
            ],
            options={
                'db_table': 'course_evaluation_component',
                'unique_together': {('program', 'evaluation_id', 'course_code')},
            },
        ),
    ]
