# Generated by Django 5.2.5 on 2025-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universitymaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('current_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'university_master',
                'managed': False,
            },
        ),
    ]
