# Generated by Django 5.1.3 on 2024-11-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseevaluationcomponent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentmarks',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentmarkssummary',
            options={'managed': False},
        ),
    ]
