# Generated by Django 5.1.3 on 2024-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_courseevaluationcomponent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'year',
                'managed': False,
            },
        ),
    ]
